/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beautymarshely;

import static beautymarshely.ConexionDB.getConexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author rey_r
 */
public class insertar_cliente extends javax.swing.JFrame {
    
    static int contadordatos = 0; 
    static int contadordatos_serv = 0;
    static int tel;
    static int e;
    static Menu obm = new Menu();
    
     
    public insertar_cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon img = new ImageIcon("src/imagenes/BeautyMarshe_Ly.png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void contarID(){
        try {
                    Connection conect = getConexion();
                    Statement leer = conect.createStatement();
                    ResultSet result = leer.executeQuery("select count(*) from clientes");
                    
                    int[] datos = new int[1];
                    
                    while (result.next()) {
                        datos[0] = result.getInt(1);
                    }
                    
                    contadordatos = datos[0]+1;
                    
                    txt_contadorID.setText(""+contadordatos);
                    
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error en el count: "+e);
                }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JLabel();
        txt_contadorID = new javax.swing.JLabel();
        txt_appaterno = new javax.swing.JLabel();
        txf_appaterno = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        txt_Titulo = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        txf_nombre = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        txt_edad = new javax.swing.JLabel();
        txt_Teléfono = new javax.swing.JLabel();
        txf_Telefono = new javax.swing.JTextField();
        txf_edad = new javax.swing.JTextField();
        txt_Comp = new javax.swing.JLabel();
        cb_sino = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 363));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_id.setText("ID:");
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 30, 40));

        txt_contadorID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_contadorID.setText("0");
        jPanel1.add(txt_contadorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 20));

        txt_appaterno.setText("Apellido:");
        jPanel1.add(txt_appaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        txf_appaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_appaternoActionPerformed(evt);
            }
        });
        jPanel1.add(txf_appaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, -1));

        btn_guardar.setText("Guardar");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_guardarMousePressed(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        txt_Titulo.setText("Insertar Datos");
        jPanel1.add(txt_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        txt_nombre.setText("Nombre:");
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 300, -1));

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cancelarMousePressed(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_limpiarMousePressed(evt);
            }
        });
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        txt_edad.setText("Edad:");
        jPanel1.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txt_Teléfono.setText("Teléfono:");
        jPanel1.add(txt_Teléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        jPanel1.add(txf_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 250, -1));
        jPanel1.add(txf_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 70, -1));

        txt_Comp.setText("Comprobante:");
        jPanel1.add(txt_Comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        cb_sino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "si", "no", " " }));
        jPanel1.add(cb_sino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_appaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_appaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_appaternoActionPerformed

    private void btn_guardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMousePressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_btn_guardarMousePressed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        try {
             ConexionDB.getConexion();
            int id_cliente = contadordatos ;
            String nombre = txf_nombre.getText();
            String ap_paterno = txf_appaterno.getText();
            long telefono =Long.parseLong(txf_Telefono.getText());
           
            int edad = Integer.parseInt(txf_edad.getText());
            String comprobante = cb_sino.getSelectedItem().toString();

            Connection con = ConexionDB.getConexion();
            PreparedStatement ps = con.prepareStatement("INSERT INTO  CLIENTES (ID_CLIENTE, NOMBRE, AP_PATERNO, TELEFONO, COMPROBANTE, EDAD) VALUES(?,?,?,?,?,?)");
            
            ps.setInt(1, id_cliente);
            ps.setString(2, nombre);
            ps.setString(3, ap_paterno);
            ps.setLong(4, telefono);
            ps.setInt(6, edad);
            ps.setString(5, comprobante);
            

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente insertado correctamente");
            btn_limpiarActionPerformed(evt);

             
        } catch (SQLException sql) {
            JOptionPane.showMessageDialog(null, "Error en el insert: "+sql, "Error en SQL", JOptionPane.ERROR_MESSAGE);

        }
        
       Clientes ob_cl = new Clientes();
       ob_cl.setVisible(true);
       this.dispose();
                                     
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nombreActionPerformed

    private void btn_cancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMousePressed
        // TODO add your handling code here:
        Clientes ob_cl = new Clientes();
        ob_cl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cancelarMousePressed

    private void btn_limpiarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMousePressed
        // TODO add your handling code here:
        txf_nombre.setText("");
        txf_appaterno.setText("");
        txf_Telefono.setText("");
        txf_edad.setText("");
        
    }//GEN-LAST:event_btn_limpiarMousePressed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        contarID();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox<String> cb_sino;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txf_Telefono;
    private javax.swing.JTextField txf_appaterno;
    private javax.swing.JTextField txf_edad;
    private javax.swing.JTextField txf_nombre;
    private javax.swing.JLabel txt_Comp;
    private javax.swing.JLabel txt_Teléfono;
    private javax.swing.JLabel txt_Titulo;
    private javax.swing.JLabel txt_appaterno;
    private javax.swing.JLabel txt_contadorID;
    private javax.swing.JLabel txt_edad;
    private javax.swing.JLabel txt_id;
    private javax.swing.JLabel txt_nombre;
    // End of variables declaration//GEN-END:variables
}
