/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beautymarshely;

import javax.swing.ImageIcon;

/**
 *
 * @author rey_r
 */
public class Menu extends javax.swing.JFrame {

  static Lashistas ob_l = new Lashistas();
  static Servicios ob_se = new Servicios();
  static Clientes ob_cl = new Clientes();
  static Citas ob_ci = new Citas();
  static Sucursales ob_su = new Sucursales();
    
    public Menu() {
        initComponents();
        ImageIcon img = new ImageIcon("src/imagenes/BeautyMarshe_Ly.png");
        this.setIconImage(img.getImage());
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        btn_lashistas = new javax.swing.JLabel();
        btn_clientes = new javax.swing.JLabel();
        btn_citas = new javax.swing.JLabel();
        btn_sucursales = new javax.swing.JLabel();
        btn_anterior = new javax.swing.JLabel();
        btn_servicios = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_lashistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lashistas.png"))); // NOI18N
        btn_lashistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_lashistasMousePressed(evt);
            }
        });
        getContentPane().add(btn_lashistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 100, -1));

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes.png"))); // NOI18N
        btn_clientes.setText("jLabel1");
        btn_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_clientesMousePressed(evt);
            }
        });
        getContentPane().add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 100, -1));

        btn_citas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Citas.png"))); // NOI18N
        btn_citas.setText("jLabel1");
        btn_citas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_citasMousePressed(evt);
            }
        });
        getContentPane().add(btn_citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 100, -1));

        btn_sucursales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sucursales.png"))); // NOI18N
        btn_sucursales.setText("jLabel1");
        btn_sucursales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_sucursalesMousePressed(evt);
            }
        });
        getContentPane().add(btn_sucursales, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 100, -1));

        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Anterior.png"))); // NOI18N
        btn_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_anteriorMousePressed(evt);
            }
        });
        getContentPane().add(btn_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        btn_servicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Servicios.png"))); // NOI18N
        btn_servicios.setText("jLabel1");
        btn_servicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_serviciosMousePressed(evt);
            }
        });
        getContentPane().add(btn_servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 100, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BeautyMarshe_Ly.png"))); // NOI18N
        logo.setText("jLabel1");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 100, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anteriorMousePressed
        Inicio ob_i = new Inicio();
        ob_i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_anteriorMousePressed

    private void btn_lashistasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lashistasMousePressed
       
        ob_l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_lashistasMousePressed

    private void btn_serviciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_serviciosMousePressed
        ob_se.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_serviciosMousePressed

    private void btn_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMousePressed
        ob_cl.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_clientesMousePressed

    private void btn_citasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_citasMousePressed
        ob_ci.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_citasMousePressed

    private void btn_sucursalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sucursalesMousePressed
        ob_su.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sucursalesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_anterior;
    private javax.swing.JLabel btn_citas;
    private javax.swing.JLabel btn_clientes;
    private javax.swing.JLabel btn_lashistas;
    private javax.swing.JLabel btn_servicios;
    private javax.swing.JLabel btn_sucursales;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
